title: Ayodele Makun # your name (or website title) here
logo: "/images/ayodele_makun-509x509.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Data Analyst and BI Consultant. 
  I have eight years of experience with Qlik, and using other data visualization tools such as Power BI, Tableau, Google/Looker Data studio, R programming, Spreadsheets, etc. 
  In the past eight years plus of my experience, I have engaged clients from various sectors including: Insurance, Investment, E-commerce, Retail sectors to design industry-specific KPIâ€™s/Dashboard, Analytics and reporting to meet organizational growth and success. 
  I have experience in designing apps and reports based on Trial balance, Balance sheet and Income and expenditure that use SAP, Quickbooks has its financial and operations ERP.  
  <br><br>
  I'm passionate about using BI tools to empower businesses all around the world to drive management decisions and shape their growth through it. 
  I desire to see Africa & Nigeria derive economic sustainable growth through the use of data.
  <br><br>
  <a href="https://www.linkedin.com/in/ayodelemakun/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
